#!/bin/sh
set -e

# Configure git to use gh as credential helper only in token mode
# In app mode, the token is generated by the application at runtime
if [ "$GITHUB_AUTH_MODE" = "token" ] || [ -n "$GITHUB_TOKEN" ]; then
    gh auth setup-git
fi

# Run the main application
exec agntpr "$@"
